React capstone project :Cryptocurrency
Habtamu210/React-capstone-Web pull request #3
Opened 2023-03-24 05:06 UTC by Habtamu210

### In this project we use:
- React components.
- React props.
- React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions and reducers in React.:

2023-03-24 07:20 UTC, brytebee requested changes
Hi, @Habtamu210 👋, 

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️
- The app is deployed and the link is added to the README.✔️
- The app files are properly structured. ✔️

##

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification. 
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-24 07:20 UTC, brytebee commented on src/componet/Nav.js
**I will leave some reviews here because lots of your files aren't available for inline comments**

Kindly look into this failed test. All tests should pass.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/27709832/227446172-7707b98e-6ec4-41a7-8373-dbac907ca6fe.png">

Kindly ensure your design is similar to the given template. I observed that on the hosted version the back button is never shown. The hamburger-like icon shows both on the home page and the details page. Where as on the local the back button remain visible on the home and details pages, kindly ensure the correct icon is rendered on the right page.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/27709832/227448026-50acf297-7e39-4721-8734-9d9badb30104.png">

<img width="433" alt="image" src="https://user-images.githubusercontent.com/27709832/227448280-4530d928-444f-40f5-a12f-ec388abd18c1.png">

The positioning of your element in your card doesn't look like the template you've been given.

Your Design | Template
:---: | :---:
<img width="175" alt="image" src="https://user-images.githubusercontent.com/27709832/227451364-a4e06134-66bb-4c5b-b8a0-4344d2b9accf.png"> | <img width="141" alt="image" src="https://user-images.githubusercontent.com/27709832/227451221-5f506f84-9940-4944-9f3f-25c1074cd077.png">

- There is an arrow icon at the top-left corner.
- The card icon
- The name is positioned to the bottom-left of the card.

2023-03-24 07:20 UTC, brytebee commented on src/componet/Nav.js
In the video presentation, you are required to highlight a part of your code that you are very proud of. You have correctly explained your codebase but never mentioned a cool part of your code that excites you or you are very proud of. Kindly do this.

2023-03-24 09:21 UTC, andersonlebon requested changes
## Hi @Habtamu210 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-24 09:21 UTC, andersonlebon commented on src/componet/Nav.js
> +  </nav>
- [ ] Nice work on solving tests but the other issues pointed out by the previous reviewer are not yet addressed like:
- the video presentation needs to contain a highlighted code that you are proud of. kindly record a new video and make sure you have spoken about a piece of code you are proud of.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/65068771/227475559-be43e943-6c97-4676-9115-1c46b0297b54.png">

- I have run your project locally and noticed that you don't have a back button, I can just see the home(hamburger)button on every page.
- Just like the previous reviewer said you need to follow the [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) including:
Typography: colors, font face, size, and weight
Layout: composition and space between elements.
<img width="577" alt="image" src="https://user-images.githubusercontent.com/65068771/227477646-59efc013-ead6-46bc-a646-4d52a09d6bf3.png">

2023-03-25 07:57 UTC, sumairq approved these changes
### Hi @Habtamu210 , 

<img src="https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-03-25 07:58 UTC, merged